// frontend/js/data.js - Frontend Translations & UI Data Dictionaries
window.MAHA_DATA = {
  translations: {
    en: {
      appName: 'MahaKisan Setu',
      appSub: 'Govt. of Maharashtra | Market Linkages & Price Discovery Platform',
      deptName: 'Maharashtra State Innovation Society (MSInS) • Dept of Skills, Employment, Entrepreneurship & Innovation',
      tagline: 'Transparent Price Discovery • Direct Farm-to-Buyer Linkages • Zero Distress Selling',
      roleFarmer: 'Farmer / FPO View',
      roleBuyer: 'Verified Buyer View',
      roleApmc: 'APMC Officer / Admin',
      kpiPriceUplift: 'Average Price Realisation Uplift',
      kpiPriceUpliftSub: '+18.4% above local distress farm-gate spot rates',
      kpiAggVolume: 'Aggregated FPO Trade Volume',
      kpiAggVolumeSub: '4,820 Quintals pooled across 28 village clusters',
      kpiEscrowGuaranteed: 'Guaranteed Payments via Escrow',
      kpiEscrowGuaranteedSub: '100% verified settlement with 48h payout SLA',
      kpiLossPrevented: 'Post-Harvest Loss Averted',
      kpiLossPreventedSub: 'Via localized cold chain & WDRA warehouse links',
      navIntelligence: 'Market Intelligence & Mandis',
      navSaleWindow: 'Smart Sale-Window Advisor',
      navLots: 'Active Farm Lots & Bids',
      navGrading: 'AI Quality Grading Assistant',
      navBuyers: 'Verified Institutional Buyers',
      navFpoPool: 'FPO Aggregation Desk',
      navLogistics: 'Logistics & Warehouses',
      navEscrow: 'Escrow Payment Ledger',
      navDisputes: 'Grievance & APMC Redressal',
      navDossier: 'Problem Statement & Pitch',
      btnCreateLot: 'Create New Trade Lot',
      btnSimulateGrade: 'Run AI Quality Assessment',
      btnCalculateStorage: 'Calculate Hold vs Sell ROI',
      btnNegotiate: 'Counter Offer / Negotiate',
      btnAcceptBid: 'Accept Bid & Lock Escrow',
      btnBookWarehouse: 'Reserve Cold Storage',
      btnPoolProduce: 'Pool With Nearby Farmers',
      btnFileDispute: 'File Grievance / APMC Claim',
      mandiRatePulseTitle: 'Maharashtra APMC Live Price Discovery',
      mandiRatePulseSub: 'Live arrival volumes, modal prices, and 30-day directional trends across primary mandis',
      saleWindowAdvisorTitle: 'Smart Sale-Window & Storage Cost-Benefit Advisor',
      saleWindowAdvisorSub: 'Stop distress sales: compare immediate spot selling vs. holding in WDRA certified warehouses',
      activeLotsTitle: 'Live Lots, Digital Bids & Escrow Status',
      activeLotsSub: 'Farm-gate and FPO aggregated produce open for competitive institutional procurement'
    },
    mr: {
      appName: 'महाकिसान सेतू',
      appSub: 'महाराष्ट्र शासन | कृषी बाजार जोडणी व भाव शोध प्रणाली',
      deptName: 'महाराष्ट्र राज्य नाविन्यता सोसायटी (MSInS) • कौशल्य, रोजगार, उद्योजकता व नाविन्यता विभाग',
      tagline: 'पारदर्शक भाव शोध • थेट शेतकरी-खरेदीदार जोडणी • संकटकालीन विक्रीला पूर्णविराम',
      roleFarmer: 'शेतकरी / शेतकरी उत्पादक कंपनी (FPO)',
      roleBuyer: 'प्रमाणित खरेदीदार / प्रक्रियादार',
      roleApmc: 'बाजार समिती / शासकीय अधिकारी',
      kpiPriceUplift: 'शेतकऱ्यांना मिळालेला सरासरी जादा दर',
      kpiPriceUpliftSub: 'स्थानिक दलालांच्या दरापेक्षा +१८.४% अधिक भाव',
      kpiAggVolume: 'एकत्रित (FPO) शेतीमाल व्यापार',
      kpiAggVolumeSub: '२८ गावांमधून ४,८२० क्विंटल मालाचे एकत्रिकरण',
      kpiEscrowGuaranteed: 'एस्क्रो खात्याद्वारे सुरक्षित चुकारे',
      kpiEscrowGuaranteedSub: '१००% खात्रीशीर व्यवहार, ४८ तासांत थेट बँक खात्यात',
      kpiLossPrevented: 'नासाडीपासून वाचवलेला शेतीमाल',
      kpiLossPreventedSub: 'स्थानिक शीतगृहे व शासकीय गोदामांच्या जोडणीमुळे',
      navIntelligence: 'बाजार भाव व आवक माहिती',
      navSaleWindow: 'विक्री-वेळ सल्लागार (साठा vs विक्री)',
      navLots: 'सक्रिय शेतीमाल लॉट्स व बोली',
      navGrading: 'एआय प्रतवारी (Quality Grading)',
      navBuyers: 'प्रमाणित संस्थात्मक खरेदीदार',
      navFpoPool: 'एफपीओ संकलन व एकत्रीकरण केंद्र',
      navLogistics: 'वाहतूक व शीतगृह आरक्षण',
      navEscrow: 'सुरक्षित एस्क्रो व्यवहार वही',
      navDisputes: 'तक्रार निवारण व लवाद',
      navDossier: 'प्रकल्प उद्दिष्ट व सादरीकरण',
      btnCreateLot: 'नवीन लॉट तयार करा',
      btnSimulateGrade: 'एआय प्रतवारी तपासा',
      btnCalculateStorage: 'साठवणूक परतावा तपासा',
      btnNegotiate: 'प्रति-ऑफर / वाटाघाटी करा',
      btnAcceptBid: 'बोली स्वीकारा व एस्क्रो लॉक करा',
      btnBookWarehouse: 'शीतगृह आरक्षित करा',
      btnPoolProduce: 'इतर शेतकऱ्यांसोबत माल एकत्र करा',
      btnFileDispute: 'तक्रार / लवाद नोंदवा',
      mandiRatePulseTitle: 'महाराष्ट्र कृषी उत्पन्न बाजार समित्यांचे थेट दर',
      mandiRatePulseSub: 'प्रमुख बाजार समित्यांमधील आवक, सरासरी (मॉडेल) दर व ३० दिवसांचा भाव कल',
      saleWindowAdvisorTitle: 'स्मार्ट विक्री-वेळ व साठवणूक नफा-तोटा सल्लागार',
      saleWindowAdvisorSub: 'कमी भावात विक्री टाळा: तात्काळ विक्री विरुद्ध शीतगृहात साठवून मिळणारा नफा तपासा',
      activeLotsTitle: 'सक्रिय लॉट्स, डिजिटल बोली व एस्क्रो स्थिती',
      activeLotsSub: 'संस्थात्मक खरेदीदारांसाठी शेतकरी व शेतकरी कंपन्यांचे थेट खरेदी उपलब्ध लॉट्स'
    }
  }
};
